### ISSUE TITLE
sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by jhd2best** [harmony-one/watchdog#56]
something caused watchdog crashed
```bash
000]: panic: sync: negative WaitGroup counter
000]: goroutine 86 [running]:
000]: sync.(*WaitGroup).Add(0xc000025930, 0xffffffffffffffff)
000]: /usr/local/go/src/sync/waitgroup.go:74 +0x147
000]: sync.(*WaitGroup).Done(...)
000]: /usr/local/go/src/sync/waitgroup.go:99
000]: main.(*monitor).worker(0xc00000c1e0, 0xc000061080, 0xc00017efc0, 0xc00017eff0)
000]: /usr/local/watchdog/master/blockchain-watchdog/reporting-server.go:555 +0x2e5
000]: created by main.(*monitor).crossLinkMonitor
000]: /usr/local/watchdog/master/blockchain-watchdog/crosslink-monitor.go:42 +0x80b
```
```bash
9437]: goroutine 87 [running]:
9437]: runtime.throw(0x9abc52, 0x21)
9437]: /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc003ec3168 sp=0xc003ec3138 pc=0x437c52
9437]: runtime.mapaccess2_faststr(0x911aa0, 0xc00028e0c0, 0xc0000d0db0, 0xc, 0x0, 0x1)
9437]: /usr/local/go/src/runtime/map_faststr.go:116 +0x4a5 fp=0xc003ec31d8 sp=0xc003ec3168 pc=0x415a45
9437]: main.(*monitor).bytesToNodeMetadata(0xc0001b8000, 0x9a3a03, 0x13, 0xc0000d0db0, 0x11, 0xc000f1e000, 0x951, 0x951, 0x0)
9437]: /usr/local/watchdog/master/blockchain-watchdog/reporting-server.go:848 +0x365 fp=0xc003ec3410 sp=0xc003ec31d8 pc=0x89ebc5
9437]: main.(*monitor).manager(0xc0001b8000, 0xc0002a2000, 0xc00028e000, 0xc000106c00, 0x20, 0xc000106c80, 0x20, 0x0, 0x0, 0x0, ...)
9437]: /usr/local/watchdog/master/blockchain-watchdog/reporting-server.go:719 +0x147d fp=0xc003ec3e40 sp=0xc003ec3410 pc=0x89bf5d
9437]: runtime.goexit()
9437]: /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc003ec3e48 sp=0xc003ec3e40 pc=0x46de01
9437]: created by main.(*monitor).update
9437]: /usr/local/watchdog/master/blockchain-watchdog/reporting-server.go:816 +0x878
```

**Comment by jhd2best** [comment]
fixed by https://github.com/harmony-one/watchdog/pull/57
